# -*- mode: python; -*-

import os
import os.path as op

def build(bld):
    source = bld.path.ant_glob('*.py')
    obj = bld(features='py',
              source=source,
              dest='${PREFIX}/lib/python2.7/site-packages/ubercal')
    obj.install_path = '${PREFIX}/lib/python2.7/site-packages/ubercal'
