# -*- mode: python; -*-

import os
import os.path as op

def build(bld):
    source = bld.path.ant_glob('*.py')
    for src in source:
        bld.install_as('${PREFIX}/bin/' + op.basename(str(src)),
                       src, 
                       chmod=0755)



